# Generated by Django 4.1.7 on 2023-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noteTaCaisse", "0002_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="total_vote",
            field=models.IntegerField(default=0),
        ),
    ]
