# Generated by Django 4.1.7 on 2023-02-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monApp2Pilotage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecoles",
            name="image",
            field=models.ImageField(default="default.png", upload_to="ecoles/"),
        ),
    ]
