# Generated by Django 4.1.7 on 2023-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monApp2Pilotage", "0002_ecoles_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eleves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("gender", models.BooleanField()),
                ("date_register", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="ecoles",
            name="image",
            field=models.ImageField(default="auto-ecole1.png", upload_to="ecoles/"),
        ),
    ]
