# Generated by Django 4.1.7 on 2023-02-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monApp2Pilotage", "0003_eleves_alter_ecoles_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleves",
            name="gender",
            field=models.CharField(
                choices=[("H", "Homme"), ("F", "Femme"), ("N/A", "Non-genré")],
                max_length=3,
            ),
        ),
    ]
