# Generated by Django 4.1.7 on 2023-02-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monApp2Pilotage", "0004_alter_eleves_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_inscription", models.DateField()),
                (
                    "ecole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monApp2Pilotage.ecoles",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monApp2Pilotage.eleves",
                    ),
                ),
            ],
        ),
    ]
