# Generated by Django 4.1.7 on 2023-03-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monApp2Pilotage", "0006_alter_inscription_eleve_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleves",
            name="ecoles",
            field=models.ManyToManyField(
                related_name="eleves",
                through="monApp2Pilotage.Inscription",
                to="monApp2Pilotage.ecoles",
            ),
        ),
    ]
